# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-23 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_url', models.CharField(max_length=255)),
                ('db_port', models.CharField(max_length=255)),
                ('db_username', models.CharField(max_length=255)),
                ('db_password', models.CharField(max_length=255)),
                ('db_name', models.CharField(max_length=255)),
                ('db_time', models.CharField(max_length=255)),
                ('db_code', models.CharField(max_length=255)),
                ('aws_bucket', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseRestore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=255)),
                ('db_code', models.CharField(max_length=255)),
                ('aws_filename', models.CharField(max_length=255)),
                ('restore_time', models.CharField(max_length=255)),
                ('is_override', models.CharField(max_length=10)),
            ],
        ),
    ]
