# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-23 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20170523_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaserestore',
            name='aws_filename',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
