# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-23 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_databaserestore_aws_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasebackup',
            name='aws_filename',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
